
const SEL = {
    tvDialogRoot: '#overlap-manager-root',
    indicatorTitle: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="container"] div[class^="title"]',
    indicatorDropdown: '#header-toolbar-indicators button',
    indicatorsDialogInput: 'div[data-name="indicators-dialog"] input[data-role="search"]',
    indicatorsDialogContent: 'div[data-name="indicators-dialog"] div[data-role="dialog-content"]',
    indicatorsDialogContentListContainer: 'div[data-name="indicators-dialog"] div[data-role="dialog-content"] div[class^="listContainer-"]',
    indicatorsDialogContentList: 'div[data-name="indicators-dialog"] div[data-role="dialog-content"] div[data-role="list-item"]',
    indicatorsDialogSideBarTabs: 'div[data-name="indicators-dialog"] div[class^="sidebar-"] div[class^="sidebarItem-"]',
    indicatorsDialogCloseBtn: 'div[data-name="indicators-dialog"] button[data-name="close"]',
    tabInput: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#inputs',
    tabInputActive: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#inputs[class*="selected"]',
    tabProperties: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#properties',
    tabPropertiesActive: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#properties[class*="selected"]',
    ticker: '#header-toolbar-symbol-search > div[class*="text-"]',
    timeFrame: '#header-toolbar-intervals div[data-role^="button"]',
    timeFrameActive: '#header-toolbar-intervals div[data-role^="button"][class*="isActive"]',
    indicatorScroll: 'div[data-name="indicator-properties-dialog"] div[class^="scrollable-"]',
    indicatorPropertyContent: 'div[data-name="indicator-properties-dialog"] div[class^="content-"] div[class^="cell-"], div[class^="checkboxItem-"]',
    okBtn: 'div[data-name="indicator-properties-dialog"] div[class^="footer-"] button[name="submit"]',
    cancelBtn: 'div[data-name="indicator-properties-dialog"] span[data-name="close"][data-role="button"]',
    scriptEditorTab: '[data-name="scripteditor"]',
    scriptEditorActive: '[data-name="scripteditor"][data-active="true"]',

    symbolSearchBtn: '#header-toolbar-symbol-search',
    symbolSearchDialog: '#overlap-manager-root div[data-name="symbol-search-items-dialog"]',
    symbolSearchAllBtn: '#overlap-manager-root div[data-name="symbol-search-items-dialog"] #symbol-search-tabs button[tabIndex="0"]',
    symbolSearchInput: '#overlap-manager-root div[data-name="symbol-search-items-dialog"] input[data-role="search"][class^="search-"]',
    symbolSearchList: '#overlap-manager-root div[data-name="symbol-search-items-dialog"] div[class^="listContainer-"]',
    symbolSearchFirstItem: '#overlap-manager-root div[data-name="symbol-search-items-dialog"] div[class^="listContainer-"] div[class^="itemRow"] div[class^="itemInfoCell-"]',
    symbolSearchFirstItemExchange: '#overlap-manager-root div[data-name="symbol-search-items-dialog"] div[class^="listContainer-"] div[class^="itemRow"] div[class^="exchangeCell-"]',

    backtestingWarningContainer: '#bottom-area div[class*="backtesting"] div[class^="backtestingWarningContainer"]',
    backtestingWarningContainerInformerBody: '#bottom-area div[class*="backtesting"] div[class^="backtestingWarningContainer"] div[class^="informerBody"]',

    // Old Date Picker Selectors, can be removed in future versions if we are sure all users have migrated to the new date picker
    datePickerSwitchToMonth: 'div[class^="picker-"] div[class^="calendar-"] button[aria-label^="Switch to months"]',
    datePickerSwitchToYears: 'div[class^="picker-"] div[class^="calendar-"] button[aria-label^="Switch to years"]',
    datePickerViewDecades: 'div[class^="picker-"] div[class^="calendar-"] div[class^="view-decades-"]',
    datePickerDecadesButtons: 'div[class^="picker-"] div[class^="calendar-"] div[class^="view-decades-"] button[class^="decade-"]',
    datePickerViewMonths: 'div[class^="picker-"] div[class^="calendar-"] div[class^="view-year-"]',
    datePickerMonthButtons: 'div[class^="picker-"] div[class^="calendar-"] div[class^="view-year-"] button',
    datePickerViewDays: 'div[class^="picker-"] div[class^="calendar-"] div[class^="view-month-"]',
    datePickerDaysButtons: 'div[class^="picker-"] div[class^="calendar-"] div[class^="view-month-"] button',

    // New Date Picker Selectors
    newDatePickerSwitchToMonth: '#overlap-manager-root div[class^="calendar-"] button[aria-label^="Switch to months"]',
    newDatePickerSwitchToYears: '#overlap-manager-root div[class^="calendar-"] button[aria-label^="Switch to years"]',
    newDatePickerViewDecades: '#overlap-manager-root div[class^="calendar-"] div[class^="view-decades-"]',
    newDatePickerDecadesButtons: '#overlap-manager-root div[class^="calendar-"] div[class^="view-decades-"] button[class^="decade-"]',
    newDatePickerViewMonths: '#overlap-manager-root div[class^="calendar-"] div[class^="view-year-"]',
    newDatePickerMonthButtons: '#overlap-manager-root div[class^="calendar-"] div[class^="view-year-"] button',
    newDatePickerViewDays: '#overlap-manager-root div[class^="calendar-"] div[class^="view-month-"]',
    newDatePickerDaysButtons: '#overlap-manager-root div[class^="calendar-"] div[class^="view-month-"] button',

    dataWindowAndObjectTreeBtn: 'button[data-name="object_tree"]',
    dataWindowBtn: '#data-window',
    dataWindowWidget: 'div[class="layout__area--right"] div[class="widgetbar-pagescontent"] div[class="widgetbar-page active"]  div[class="widgetbar-widgetbody"]',
    dataWindowTreeGrid: 'div[class="layout__area--right"] div[class="widgetbar-pagescontent"] div[class="widgetbar-page active"]  div[class="widgetbar-widgetbody"]',

    strategyTesterTab: '[data-name="backtesting"]',
    strategyTesterTabActive: '[data-name="backtesting"][data-active="true"]',
    strategyCaption: '#bottom-area div[class*="backtesting"]  [class^="strategyGroup"] [data-strategy-title]',

    strategySummary: 'button[id="Performance"]',
    strategySummaryActive: 'button[id="Performance"][class*="selected"]',
    strategyProperties: 'button[id="Properties"]',
    strategyPropertiesDataRange: '#bottom-area div[class^="reportViewContainer"] button[aria-controls="id_Date-range"] span[class^="minimizedData"]',
    strategyPropertiesSymbolInfo: '#bottom-area div[class^="reportViewContainer"] button[aria-controls="id_Symbol-info"] span[class^="minimizedData"]',
    strategyPropertiesStrategyInputsBtn: '#bottom-area div[class^="reportViewContainer"] button[aria-controls="id_Strategy-inputs"]',
    strategyPropertiesStrategyInputs: '#bottom-area div[class^="reportViewContainer"] #id_Strategy-inputs',
    strategyPropertiesStrategyProperties: '#bottom-area div[class^="reportViewContainer"] button[aria-controls="id_Strategy-properties"] span[class^="minimizedData"]',

    strategyPropertiesBtn: '#overlap-manager-root div[role="menuitem"][aria-label^="Settings"]',
    strategyTradesAnalysis: 'button[id="Trades Analysis"]',
    strategyTradesAnalysisActive: 'button[id="Trades Analysis"][class*="selected"]',
    strategyRatios: 'button[id="Ratios"]', // Risk/performance ratios
    strategyRatiosActive: 'button[id="Ratios"][class*="selected"]', // Risk/performance ratios
    strategyTrades: 'button[id="List of Trades"]',
    strategyTradesActive: 'button[id="List of Trades"][class*="selected"]',
    strategyReportTable: '#bottom-area div[class*="backtesting"] div[class^="wrapper-"] div[class^="ka-table-wrapper"]',

    strategyReportObserveArea: '#bottom-area div[class*="backtesting"] div[class^="wrapper-"]',
    strategyReportInProcess: '#bottom-area div[class*="backtesting"] div[class^="wrapper-"]  div[role="progressbar"]',
    strategyReportReady: '#bottom-area div[class*="backtesting"] div[class^="wrapper-"] div[class^="wrapper-"] [class*="root"]',

    strategyReportError: '#bottom-area div[class*="backtesting"] div[class^="wrapper-"] div[class^="container"] [class*=emptyStateIcon]',
    strategyReportHeader: '#bottom-area div[class*="backtesting"] div[class^="wrapper-"] div[class^="ka-table-wrapper"] table thead > tr > th',
    strategyReportRow: '#bottom-area div[class*="backtesting"] div[class^="wrapper-"] div[class^="ka-table-wrapper"] table tbody > tr[class^="ka-tr"]:not([class*="ka-no-data-row"])',
    strategyReportWarningHint: '#bottom-area div[class*="backtesting"] div[class^="warningHint"]',

    strategyDeepTestCheckbox: '#bottom-area div[class*="backtesting"]  [class^="deepHistoryContainer"]  [class^="switcher"] input',
    strategyDeepTestStartDate: '#bottom-area div[class*="backtesting"]  [class^="historyParams"]  [class^="container" ]> div:nth-child(1) div[class^="pickerInput"] input',
    strategyDeepTestEndDate: '#bottom-area div[class*="backtesting"]  [class^="historyParams"]  [class^="container" ]> div:nth-child(3) div[class^="pickerInput"] input',
    strategyDeepTestGenerateBtn: '#bottom-area div[class*="backtesting"]  [class^="historyParams"] button[class^="generateReportBtn"]:not([disabled])',
    strategyDeepTestGenerateBtnDisabled: '#bottom-area div[class*="backtesting"]  [class^="historyParams"] button[class^="generateReportBtn"][disabled]',

    testDateRangeButton: '#bottom-area div[class*="backtesting"] [class^="dateRangeMenuWrapper-"] button',
    testDateRangeItemRangeFromChart: '#overlap-manager-root div[role="menuitemcheckbox"][aria-label="Range from chart"]',
    testDateRangeItemLast7Days: '#overlap-manager-root div[role="menuitemcheckbox"][aria-label="Last 7 days"]',
    testDateRangeItemLast30Days: '#overlap-manager-root div[role="menuitemcheckbox"][aria-label="Last 30 days"]',
    testDateRangeItemLast90Days: '#overlap-manager-root div[role="menuitemcheckbox"][aria-label="Last 90 days"]',
    testDateRangeItemLast365Days: '#overlap-manager-root div[role="menuitemcheckbox"][aria-label="Last 365 days"]',
    testDateRangeItemEntireHistory: '#overlap-manager-root div[role="menuitemcheckbox"][aria-label="Entire history"]',
    testDateRangeItemCustomRange: '#overlap-manager-root div[role="menuitemcheckbox"][aria-label="Custom date range…"]',
    testDateRangeItemResetToChartSeession: '#overlap-manager-root div[role="menuitemcheckbox"][aria-label="Reset to chart session"]',
    testDateRangeCustomStartDate: '#overlap-manager-root div[data-name="custom-date-range-dialog"] [class^="dialogContent-"] [class^="inputsWrapper"]> div:nth-child(1) div[class^="pickerInput-"]',
    testDateRangeCustomEndDate: '#overlap-manager-root div[data-name="custom-date-range-dialog"] [class^="dialogContent-"] [class^="inputsWrapper"]> div:nth-child(2) div[class^="pickerInput"]',
    testDateRangeCustomApplyBtn: '#overlap-manager-root div[data-name="custom-date-range-dialog"] [class^="footer-"] button[name="submit"]',

    strategyListOptions: 'div[role="listbox"] div[class^="menuBox"] div[role="option"] span[class^="label-"]',
    strategyDefaultElement: '#property-actions',
    strategyDefaultElementList: '#id_property-actions_listbox span[class^="label-"]',

    changeIntervalDialog: 'div[data-dialog-name="change-interval-dialog"]',
    chartTicker: '#header-toolbar-symbol-search > div[class*="text-"]',
    chartTimeframeFavorite: '#header-toolbar-intervals button[data-value]',
    chartTimeframeActive: '#header-toolbar-intervals button[data-value][aria-checked="true"]',
    chartTimeframeMenuOrSingle: '#header-toolbar-intervals button[class^="menu"]',

    chartTimeframeMenuAddCustomTf: '#overlap-manager-root div[class^="menuBox"] div[class^="dropdown"] div[aria-level="1"][aria-posinset="1"][aria-haspopup="dialog"]',
    chartTimeframeAddCustomDialogInput: '#overlap-manager-root div[data-name="add-custom-interval-dialog"] input',
    chartTimeframeAddCustomDialogType: '#overlap-manager-root div[data-name="add-custom-interval-dialog"] span[aria-haspopup="listbox"]',
    chartTimeframeAddCustomDialogAddBtn: '#overlap-manager-root div[data-name="add-custom-interval-dialog"] button[name="submit"]',

    chartTimeframeMenuItem: '#overlap-manager-root div[class^="dropdown"] div[data-value]',
    chartTimeframeMenuInput: '#overlap-manager-root div[class^="dropdown"] div[class^="form"] > input',
    chartTimeframeMenuType: '#overlap-manager-root div[class^="menuBox"] div[class^="dropdown"] div[class^="form"] > div[class^="menu"]',
    chartTimeframeMenuAdd: '#overlap-manager-root div[class^="menuBox"] div[class^="dropdown"] div[class^="form"] > div[class^="add"]',
    chartTimeframeMenuTypeItems: '#overlap-manager-root div[class^="menuBox"] > div[class^="item"]',
    chartTimeframeMenuTypeItemsMin: '#overlap-manager-root div[class^="menuBox"] > div[class^="item"]:nth-child(1)',
    chartTimeframeMenuTypeItemsHours: '#overlap-manager-root div[class^="menuBox"] > div[class^="item"]:nth-child(2)',
    chartTimeframeMenuTypeItemsDays: '#overlap-manager-root div[class^="menuBox"] > div[class^="item"]:nth-child(3)',
    chartTimeframeMenuTypeItemsWeeks: '#overlap-manager-root div[class^="menuBox"] > div[class^="item"]:nth-child(4)',
    chartTimeframeMenuTypeItemsMonth: '#overlap-manager-root div[class^="menuBox"] > div[class^="item"]:nth-child(5)',
    chartTimeframeMenuTypeItemsRange: '#overlap-manager-root div[class^="menuBox"] > div[class^="item"]:nth-child(6)',

    legendContainer: 'div[class^="legend-"][data-name="legend"]',
    legendSources: 'div[class^="legend-"][data-name="legend"] > div[class^="sourcesWrapper-"] > div[class^="sources-"] > div[data-name="legend-source-item"]',
    legendSourceTitle: 'div[data-name="legend-source-title"]',
    legendStatus: 'div[class^="noWrapWrapper-"] > div[class^="statusesWrapper-"] > div[data-name="legend-source-item-status"]',
    legendStatusDataProblemLow: 'div[class*="dataProblemLow-"]',
    legendLoaderStatus: 'div[class^="valuesWrapper-"] span[class^="loader-"]',

    reportOutdatedButton: '#snackbar-container button[data-overflow-tooltip-text="Update report"]',
    updatingReportContainer: '#snackbar-container div[class^="main-"]',
}